name: chime_mobile
description: "A mobile chat app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.3.3
  path_provider: ^2.1.2
  open_filex: ^4.0.2
  package_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  encrypt: ^5.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter icon configuration (must be at root level)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcons/appstore.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/AppIcons/appstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/chime_logo.png
    - assets/AppIcons/appstore.png
